trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - script: docker compose -f docker-compose.yml config --quiet
    displayName: Validar Docker Compose

  - script: docker compose -f docker-compose.yml build
    displayName: Construir servicios
