// <auto-generated />
using System;
using ApiPedidos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiPedidos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005184849_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiPedidos.Models.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("actualizado_en")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("banco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("cargo_empaque")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("creado_en")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("cuotas")
                        .HasColumnType("integer");

                    b.Property<string>("departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("empaque_regalo")
                        .HasColumnType("boolean");

                    b.Property<string>("entrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("envio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mensaje_regalo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mensajeria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("metodo_pago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("peso_lb")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("usuario_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("ApiPedidos.Models.PedidoHistorial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pedido_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("pedido_id");

                    b.ToTable("pedido_historial", (string)null);
                });

            modelBuilder.Entity("ApiPedidos.Models.PedidoItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pedido_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("precio_unitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("producto_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("id");

                    b.HasIndex("pedido_id");

                    b.ToTable("pedido_items", (string)null);
                });

            modelBuilder.Entity("ApiPedidos.Models.PedidoHistorial", b =>
                {
                    b.HasOne("ApiPedidos.Models.Pedido", "pedido")
                        .WithMany("historial")
                        .HasForeignKey("pedido_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pedido");
                });

            modelBuilder.Entity("ApiPedidos.Models.PedidoItem", b =>
                {
                    b.HasOne("ApiPedidos.Models.Pedido", "pedido")
                        .WithMany("items")
                        .HasForeignKey("pedido_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pedido");
                });

            modelBuilder.Entity("ApiPedidos.Models.Pedido", b =>
                {
                    b.Navigation("historial");

                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
